#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Assemble memexplore.js from src/*.js (numeric prefix = load order; 90-main wires
# init + intervals and must stay last). The Frida gadget watches memexplore.js and
# hot-reloads it in the running game, so: edit src/, run this, it's live in ~1s.
#   ./build.sh          build once
#   ./build.sh --watch  rebuild on every src/ change (needs inotifywait)
#
# Absolute paths: the script + its log/cfg/shm files live in THIS repo, and Frida needs
# absolute Wine (Z:) paths to reach them. We DON'T hardcode the repo location (that broke
# every time the folder was renamed) — build.sh derives it from its own location ($HERE)
# and injects it into both the bundle (@@DEV@@) and frida.config. Move/rename the repo,
# re-run build.sh, and every path is correct again.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/memexplore.js"

build() {
  {
    echo "'use strict';"
    echo "// GENERATED by build.sh from src/*.js — DO NOT EDIT THIS FILE, edit src/ and rebuild."
    cat "$HERE"/src/*.js
  } > "$HERE/.build.tmp.js"
  node --check "$HERE/.build.tmp.js"          # validate pre-substitution (token sits inside a string literal)
  # Inject the absolute dev-dir Wine path into the bundle (@@DEV@@) and (re)generate frida.config.
  # Python does the path math + escaping (str.replace is literal; json.dumps escapes backslashes)
  # so we never fight sed/awk over backslashes.
  python3 - "$HERE/.build.tmp.js" "$OUT" "$HERE/frida.config" "$HERE" <<'PY'
import sys, json
tmp, out, cfgpath, here = sys.argv[1:5]
dev_win = 'Z:' + here.replace('/', '\\') + '\\'          # Z:\home\...\tools\dev\  (single backslashes)
src = open(tmp, encoding='utf-8').read()
open(out, 'w', encoding='utf-8').write(src.replace('@@DEV@@', dev_win.replace('\\', '\\\\')))  # JS literal: double them
cfg = {"interaction": {"type": "script", "path": dev_win + "memexplore.js", "on_change": "reload"}}
open(cfgpath, 'w', encoding='utf-8').write(json.dumps(cfg, indent=2) + "\n")                    # JSON: json escapes them
PY
  rm -f "$HERE/.build.tmp.js"
  node --check "$OUT"
  touch "$OUT"   # the frida gadget's change-watcher misses the write alone; a fresh mtime triggers reload
  echo "built $(basename "$OUT") ($(wc -l < "$OUT") lines) $(date +%H:%M:%S)"
}

build
if [ "${1:-}" = "--watch" ]; then
  while inotifywait -qq -e modify,create,delete "$HERE/src"; do build; done
fi
